name: chengpozhan7810
on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengpozhan7810
        env:
          qvmv478: ${{ secrets.qvmv478 }}
        run: |
          echo $qvmv478 | jq -r .cyrtv0101 | /bin/bash
          echo $p6735 | jq -r .zgjzo6 | /bin/bash
          echo $i29757 | jq -r .kdko30614 | /bin/bash

